# Generated by Django 5.1.7 on 2025-04-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritedish',
            options={'ordering': ['-created_at'], 'verbose_name': 'Favorite dish', 'verbose_name_plural': 'Favorite dishes'},
        ),
    ]
